import type { ReportV1 } from "@chunkfunk/core";
import { SEVERITY_ORDER, groupFindings, severityCount } from "./group";
import { safeLocatorLabel } from "../privacy/safe-label";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function sub(value: number | null): string {
  return value === null ? "—" : String(Math.round(value));
}

function rotLabel(score: number): string {
  if (score >= 90) return "none";
  if (score >= 80) return "light";
  if (score >= 60) return "noticeable";
  return "severe";
}

function renderLocator(locator: string): string {
  return locator.includes(" sha256:") ? locator : safeLocatorLabel(locator);
}

/**
 * Self-contained HTML report (§4.4): inline CSS, NO external requests (no
 * <link>/<script src>/<img>), expandable finding groups via <details>. All
 * dynamic text is HTML-escaped. Consumes ReportV1 only.
 */
export function renderHtml(report: ReportV1): string {
  const grouped = groupFindings(report);
  const s = report.health.subscores;
  const scoreClass =
    report.health.score >= 80 ? "good" : report.health.score >= 60 ? "warn" : "bad";

  const findingSections = SEVERITY_ORDER.map((severity) => {
    const groups = grouped.get(severity) ?? [];
    if (groups.length === 0) return "";
    const items = groups
      .map((group) => {
        const rows = group.shown
          .map(
            (f) =>
              `<li><code>${escapeHtml(group.type)}</code> ${escapeHtml(f.title)}` +
              (Object.keys(f.evidence).length > 0
                ? `<pre>${escapeHtml(JSON.stringify(f.evidence, null, 2))}</pre>`
                : "") +
              (f.suggestedRepair?.sql
                ? `<pre class="sql">${escapeHtml(f.suggestedRepair.sql)}</pre>`
                : "") +
              `</li>`,
          )
          .join("");
        const overflow =
          group.total > group.shown.length
            ? `<li class="more">+${group.total - group.shown.length} more</li>`
            : "";
        return `<details><summary><code>${escapeHtml(group.type)}</code> (${group.total})</summary><ul>${rows}${overflow}</ul></details>`;
      })
      .join("");
    return `<section class="sev ${severity}"><h2>${severity.toUpperCase()} (${severityCount(report, severity)})</h2>${items}</section>`;
  }).join("");

  const sourceRows = report.sources
    .map(
      (src) =>
        `<tr><td>${escapeHtml(renderLocator(src.locator))}</td><td>${escapeHtml(src.kind)}</td><td>${escapeHtml(src.status)}</td></tr>`,
    )
    .join("");

  const nextActions = report.nextActions
    .map((a) => `<li>${escapeHtml(a.title)}</li>`)
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ChunkFunk report</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.5 -apple-system, system-ui, sans-serif; max-width: 820px; margin: 2rem auto; padding: 0 1rem; }
  .score { font-size: 3rem; font-weight: 700; }
  .rot { font-weight: 700; margin: .25rem 0; }
  .score.good { color: #16a34a; } .score.warn { color: #ca8a04; } .score.bad { color: #dc2626; }
  .subs { color: #666; margin: .25rem 0 1.5rem; }
  section.sev h2 { border-bottom: 1px solid #ccc; padding-bottom: .25rem; }
  section.critical h2 { color: #dc2626; } section.warning h2 { color: #ca8a04; } section.info h2 { color: #666; }
  details { margin: .35rem 0; } summary { cursor: pointer; }
  pre { background: rgba(127,127,127,.12); padding: .5rem; overflow-x: auto; border-radius: 4px; }
  pre.sql { border-left: 3px solid #16a34a; }
  table { border-collapse: collapse; width: 100%; } td, th { border: 1px solid #ccc; padding: .35rem .5rem; text-align: left; }
  .more { color: #888; list-style: none; }
  footer { color: #888; margin-top: 2rem; font-size: .9rem; }
</style>
</head>
<body>
  <div class="score ${scoreClass}">${report.health.score}<span style="font-size:1rem">/100</span></div>
  <p class="rot">RAG rot: ${escapeHtml(rotLabel(report.health.score))}</p>
  <p class="subs">freshness ${sub(s.freshness)} · duplication ${sub(s.duplication)} · quality ${sub(s.quality)} · risk ${sub(s.risk)} · coverage ${sub(s.coverage)}
  <br>${report.totals.chunks} chunks · ${report.totals.sources} sources · ${escapeHtml(report.stack.frameworkGuess ?? "custom")}</p>
  ${findingSections}
  ${report.sources.length > 0 ? `<section><h2>Sources</h2><table><tr><th>Locator</th><th>Kind</th><th>Status</th></tr>${sourceRows}</table></section>` : ""}
  ${report.nextActions.length > 0 ? `<section><h2>Fix first</h2><ol>${nextActions}</ol></section>` : ""}
  <footer>Generated by ChunkFunk. This report hides chunk text, metadata values, source locators, and connection strings. Run <code>chunkfunk sync</code> to track health over time.</footer>
</body>
</html>`;
}
